version: '3.8'

services:
  observability-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: observability_api_p5
    ports:
      - "8005:8000"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

networks:
  default:
    name: net_pregunta_05
