apiVersion: v1
kind: Service
metadata:
  name: api-rest-service
  namespace: default
  labels:
    app: api-rest-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: api-rest-service

---

apiVersion: v1
kind: Service
metadata:
  name: mock-downstream-service
  namespace: default
  labels:
    app: mock-downstream-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: mock-downstream-service
